spring:
  application:
    name: e-commerce

  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce
    username: root
    password: Rgukt@483

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
              
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8180/realms/e-commerce/protocol/openid-connect/certs"

server:
  port: 8081

#keycloak
keycloak:
  auth-server-url: http://localhost:8180
  realm: e-commerce
  client-id: fetch-users
  client-secret: JNQzGH6C7QopeY1YA18Eze1YZIFWmHKL
stripe:
 secretKey: <configure your token>
